//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Texcel_TabControl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdTexcel_Eddy_FranckEntities : DbContext
    {
        public BdTexcel_Eddy_FranckEntities()
            : base("name=BdTexcel_Eddy_FranckEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAdministrateur> tblAdministrateur { get; set; }
        public virtual DbSet<tblCategorie> tblCategorie { get; set; }
        public virtual DbSet<tblCategorieEmploi> tblCategorieEmploi { get; set; }
        public virtual DbSet<tblClassification> tblClassification { get; set; }
        public virtual DbSet<tblDirecteur> tblDirecteur { get; set; }
        public virtual DbSet<tblEmploye> tblEmploye { get; set; }
        public virtual DbSet<tblEquipe> tblEquipe { get; set; }
        public virtual DbSet<tblGenre> tblGenre { get; set; }
        public virtual DbSet<tblGerant> tblGerant { get; set; }
        public virtual DbSet<tblJeu> tblJeu { get; set; }
        public virtual DbSet<tblPlateforme> tblPlateforme { get; set; }
        public virtual DbSet<tblProjetTest> tblProjetTest { get; set; }
        public virtual DbSet<tblSE> tblSE { get; set; }
        public virtual DbSet<tblTest> tblTest { get; set; }
        public virtual DbSet<tblTheme> tblTheme { get; set; }
        public virtual DbSet<tblTypePlateforme> tblTypePlateforme { get; set; }
        public virtual DbSet<tblVille> tblVille { get; set; }
    }
}
